apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-lab-2slow-ca
  namespace: traefik
spec:
  secretName: wildcard-lab-2slow-ca-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.lab.2slow.ca"
